# Generated by Django 6.0 on 2026-01-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Adress', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('PasswordConfirm', models.CharField(max_length=200)),
            ],
        ),
    ]
