# Generated by Django 6.0 on 2026-01-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Lastname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='PasswordConfirm',
            new_name='password_confirm',
        ),
    ]
