# Generated by Django 6.0 on 2026-01-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
