# Generated by Django 6.0 on 2026-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0002_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_kilo',
            field=models.BooleanField(default=False, verbose_name='¿Se vende por peso?'),
        ),
    ]
