# Generated by Django 6.0 on 2026-01-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0003_products_is_kilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imagen',
            new_name='imag',
        ),
    ]
