# Generated by Django 6.0 on 2026-01-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0004_rename_imagen_products_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='imag',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imag',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='is_kilo',
            field=models.BooleanField(default=False, verbose_name='Sold by weight?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Is Promotion?'),
        ),
    ]
