# Generated by Django 6.0 on 2026-01-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0005_rename_imag_promotions_image_remove_products_imag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='products',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
