# Generated by Django 6.0 on 2026-01-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0006_alter_products_options_products_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='category',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
