# Generated by Django 6.0 on 2026-01-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0007_alter_category_options_category_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='teach?'),
        ),
    ]
