# Generated by Django 6.0 on 2026-01-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticles', '0008_category_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_visible',
            new_name='is_active',
        ),
    ]
